### ISSUE TITLE
Unify release process and version updating after changes in any related part of the code

### ISSUE THREAD

**Issue by ignacio-penas** [nuvlaedge/nuvlaedge#42]
The main drawback for the unification of version would be the need to download the image multiple times, as in the current implementation of the shared nuvlaedge library. 

By using the same image, it is only downloaded once.

**Comment by ignacio-penas** [comment]
Release process proposal:




![Image](https://github.com/nuvlaedge/nuvlaedge/assets/11061525/e48531b9-b193-4e47-ba31-e9d08cc63800)

**Comment by ignacio-penas** [comment]
The release notes can be autogenerated from github and categorised using labels in the pull requests (I would need to research a bit if it can account for hotfixes with push against main directly). An example of categorization an labels from the video:
```
changelog:
  categories:
    - title: Breaking changes
      labels:
        - Semver-Major
        - breaking-change
    - title: New Features
      labels:
        - Semver-minor
        - feat
        - enhancement
    - title: Other Changes
      labels:
        - "*"
```
This configuration creates 3 sections and assigns the pr title depending on the label assigned to it.
On the other hand, we have the changelog autogeneration. This comes from conventional commit formatting (https://www.conventionalcommits.org/en/v1.0.0/#specification). So as I mentioned before, it will generate and push back to the repo the changelog analizing the commits following that format. This is the github action that executes it: https://github.com/TriPSs/conventional-changelog-action
With regards to the automatic versioning, I found out that the official github action has been deprecated and I haven't managed to find anything similar. However, in the video from GH they use npm bump version tool and I have found a plugin for poetry (the package manager for nuvlaedge) that does the same:
```
poetry version major --- v0.20.1 -> v1.0.0
poetry version minor --- v0.20.1 -> v0.21.0
poetry version patch --- v0.20.1 -> v0.20.2
```
